FROM node:alpine

ENV HTTP_PROXY "http://rbcproxy.robinsonsbank.com.ph:80"
ENV HTTPS_PROXY "http://rbcproxy.robinsonsbank.com.ph:80"

WORKDIR '/app'

COPY package.json .
RUN npm install
COPY . .

CMD ["npm","run","start"]